CREATE TABLE user(
  id INT(11) NOT NULL,
  uname VARCHAR(255) NOT NULL DEFAULT '',
  upassword VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE admin(
   id INT(11) NOT NULL,
   aname VARCHAR(255) NOT NULL DEFAULT '',
   apassword VARCHAR(255) NOT NULL DEFAULT '',
   PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE role(
  id INT(11) NOT NULL,
  rname VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE premission(
  id INT(11) NOT NULL,
  pname VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE user_role(
  uid INT(11) NOT NULL ,
  rid INT(11) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE admin_role(
  aid INT(11) NOT NULL ,
  rid INT(11) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE role_premission(
  rid INT(11) NOT NULL ,
  pd INT(11) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
